# town_names.gd

const TOWN_NAMES = [
	"Acorn Hollow",
	"Berrybrook",
	"Blossom Glade",
	"Bluebell Ridge",
	"Breezy Pines",
	"Brambleton",
	"Bunnyburrow",
	"Buttercup Bay",
	"Carrot Creek",
	"Cedar Nook",
	"Cherrywood",
	"Cloverfield",
	"Cloudberry Hill",
	"Cozyden",
	"Cranberry Cove",
	"Daisy Dell",
	"Dewdrop Meadow",
	"Dovetail Village",
	"Elderberry Grove",
	"Fernvale",
	"Firefly Hollow",
	"Fuzzywillow",
	"Golden Acorn",
	"Gooseberry Glen",
	"Honeycomb Hamlet",
	'Honeysuckle Hill',
	"Hummingbird Haven",
	'Juniper Junction',
	"Lavender Lane",
	"Lemonleaf",
	"Lilac Landing",
	"Maplewood","Marshmallow Meadow",
	"Meadowlark",
	"Milky Way Village",
	"Misty Hollow",
	"Moonglow Glade",
	"Mossy Glen",
	"Mulberry Mill",
	"Nutmeg Nook",
	"Oakberry",
	"Peachblossom",
	"Pebblebrook",
	"Petalpatch",
	"Pinecone Point",
	"Poppyfield",
	"Puffin’s Roost",
	"Pumpkin Patch",
	"Raindrop Ridge",
	"Raspberry Row",
	"Rosehip Hollow",
	"Snuggleton",
	"Sprigsville",
	"Starfall",
	"Strawberry Fields",
	"Sunflower Summit",
	"Thimbleton",
	"Tulip Terrace",
	"Walnut Way",
	"Whiskerwick",
]
